name: 2022

on:
  pull_request:
    branches:
    - main
    paths:
    - .github/workflows/2022.yaml
    - .rubocop.yaml
    - 2022/**/*
    - Gemfile
    - Rakefile
  push:
    branches:
    - main
    paths:
    - .github/workflows/2022.yaml
    - .rubocop.yaml
    - 2022/**/*
    - Gemfile
    - Rakefile

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: false
        ruby-version: 3.0
    - name: Analyse source code
      run: bundle exec rubocop

  test:
    defaults:
      run:
        shell: bash
        working-directory: 2022
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: false
        ruby-version: 3.0
    - name: Day 01
      run: diff <(bundle exec rake aoc[2022,01]) <(echo 69289 ; echo 205615)
    - name: Day 02
      run: diff <(bundle exec rake aoc[2022,02]) <(echo 12740 ; echo 11980)
    - name: Day 03
      run: diff <(bundle exec rake aoc[2022,03]) <(echo 7597 ; echo 2607)
    - name: Day 04
      run: diff <(bundle exec rake aoc[2022,04]) <(echo 595 ; echo 952)
    - name: Day 05
      run: diff <(bundle exec rake aoc[2022,05]) <(echo FWNSHLDNZ ; echo RNRGDNFQG)
    - name: Day 06
      run: diff <(bundle exec rake aoc[2022,06]) <(echo 1804 ; echo 2508)
    - name: Day 07
      run: diff <(bundle exec rake aoc[2022,07]) <(echo 1770595; echo 2195372)
