name: 2022

on:
  pull_request:
    branches:
    - main
    paths:
    - 2022/**/*
  push:
    branches:
    - main
    paths:
    - 2022/**/*

jobs:
  test:
    defaults:
      run:
        shell: bash
        working-directory: 2022
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: false
        ruby-version: 3.0
    - name: Day 01
      run: diff <(ruby day01.rb) <(echo "69289 205615")
    - name: Day 02
      run: diff <(go run day02.go) <(echo "12740 11980")
    - name: Day 03
      run: diff <(ruby day03.rb) <(echo "7597 2607")
