name: 2022

on:
  pull_request:
    branches:
    - main
    paths:
    - .github/workflows/2022.yaml
    - 2022/**/*
  push:
    branches:
    - main
    paths:
    - .github/workflows/2022.yaml
    - 2022/**/*

jobs:
  test:
    defaults:
      run:
        shell: bash
        working-directory: 2022
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: false
        ruby-version: 3.0
    - name: Day 01
      run: diff <(ruby day01.rb) <(echo 69289 ; echo 205615)
    - name: Day 02
      run: diff <(ruby day02.go) <(echo 12740 ; echo 11980)
    - name: Day 03
      run: diff <(ruby day03.rb) <(echo 7597 ; echo 2607)
    - name: Day 04
      run: diff <(ruby day04.rb) <(echo 595 ; echo 952)
    - name: Day 05
      run: diff <(ruby day05.rb) <(echo FWNSHLDNZ ; echo RNRGDNFQG)
    - name: Day 06
      run: diff <(ruby day06.rb) <(echo 1804 ; echo 2508)
